# Generated by Django 5.0 on 2024-01-30 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival',
            field=models.ForeignKey(help_text='Arrival airport', on_delete=django.db.models.deletion.CASCADE, related_name='arriving_flights', to='app.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.ForeignKey(help_text='Departure airport', on_delete=django.db.models.deletion.CASCADE, related_name='departing_flights', to='app.airport'),
        ),
    ]
