# Generated by Django 5.0.1 on 2024-02-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_flight_arrival_alter_flight_departure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='arrival',
            new_name='arrival_airport',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='departure',
            new_name='departure_airport',
        ),
    ]
