# Generated by Django 5.0 on 2024-02-01 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_arrival_flight_arrival_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(default=111, help_text='The booked flight', on_delete=django.db.models.deletion.CASCADE, to='app.flight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.ManyToManyField(related_name='booked_flights', to='app.passenger'),
        ),
    ]
